#define DISCOVER_REQ 0
#define DISCOVER_RESP 1
//#define NUMBER_NODES 2 non lo utilizziamo più
#define START_OPERATION 3
#define OPERATION_OK 4
#define OPERATION_ERROR 5
#define OPERATION_COMPLETED 6
#define MAX_NUM_ATTEMPTS 5
#define CANCEL_OPERATION 7
#define CANCEL_OK 8
#define CANCEL_ERR 9
#define OPEN_WINDOW 10
#define CLOSE_WINDOW 11
#define SET_TIMER_WINDOW 12
#define SET_TEMPERATURE 13
#define SET_HUMIDITY 14